spring:
  application:
    name: CourseMicroservices
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TechLearningMicroservice
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    enabled: true

server:
  port: 8001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
      
message: default message from course-service